config/routes.rb
Rails.application.routes.draw do
  resources :events do
    collection do
      post 'search'
    end
  end
  get :list_events, to: 'events#list'
  get :featured_event_slides, to: 'events#slides'

  resources :welcome

  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :allow_iframe_requests
  skip_before_action :verify_authenticity_token, only: %i[ search list]
  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end
  # GET /events or /events.json
  def index
    #if params[:public] == 'false'
    #  @events = Event.where("event_details ->> 'image' != ''")
    #                 .order(Arel.sql "(event_details ->> 'start_datetime')::date  ASC")
    #elsif params[:past] == 'true'
    #@events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
    #               .where("(event_details ->> 'end_date')::date <= :today", today: Date.today)
    #               .order(Arel.sql "(event_details ->> 'start_datetime')::date  ASC")
    #else
    #  @events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
    #                 .where("(event_details ->> 'end_date')::date >= :today", today: Date.today)
    #                 .or(Event.where("event_details ->> 'recurrence_description' LIKE 'Every%'"))
    #                 .order(Arel.sql "(event_details ->> 'start_datetime')::date  DESC")
    #end
  end

  # GET /events/1 or /events/1.json
  def show
  end

  def search
    if params[:query].present?
      @events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
                     .where("event_details::text ilike ?", "%#{params[:query]}%")
                     .where("(event_details ->> 'end_date')::date >= :today", today: Date.today)
                     .or(Event.where("event_details ->> 'recurrence_description' LIKE 'Every%'"))
                     .where("event_details::text ilike ?", "%#{params[:query]}%")
                     .order(Arel.sql "(event_details ->> 'start_datetime')::date  ASC")
    else
      @events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
                     .where("(event_details ->> 'end_date')::date >= :today", today: Date.today)
                     .or(Event.where("event_details ->> 'recurrence_description' LIKE 'Every%'"))
                     .order(Arel.sql "(event_details ->> 'start_datetime')::date  ASC")
    end

    render turbo_stream: turbo_stream.replace(
      'list',
      template: 'events/list',
      locals: {
        events: @events
      }
    )
  end

  def list
    @month = Date.today.month
    @events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
                   .where("(event_details ->> 'end_date')::date >= :today", today: Date.today)
                   .or(Event.where("event_details ->> 'recurrence_description' LIKE 'Every%'"))
                   .order(Arel.sql "(event_details ->> 'start_datetime')::date  DESC")
    render layout: false
  end

  def slides
    @events = Event.where("event_details ->> 'public_calendar_listed' = 'true'" )
                   .where("(event_details ->> 'end_date')::date >= :today", today: Date.today)
                   .or(Event.where("event_details ->> 'recurrence_description' LIKE 'Every%'"))
                   .order(Arel.sql "(event_details ->> 'start_datetime')::date  DESC")
    render layout: false
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:event_details)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @year = Date.today.year
    @month = Date.today.month
    @day = Date.today.day
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_details %>
    <%= form.text_field :event_details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% if params[:view] == 'list' %>
  <%= form_with(url: search_events_path, data: { controller: 'form-submission', form_submission_target: "form" }) do |form| %>
    <%= form.label :query, "Search:", class: 'text-gray-900 font-medium title-font' %>
    <%= form.text_field :query, data: { action: "input->form-submission#search" }, class: 'form-control' %>

  <% end %>
  <br/>
  <%= turbo_frame_tag :list, src: list_events_path(month: Date.today.month), loading: :lazy do %>
    <div class="flex flex-col space-y-6">
      <% 10.times do %>
        <div class=" p-6 rounded-lg border mb-2" style="background-color: #eff2f6" >
          <div class="animate-pulse flex space-x-4">
            <!-- Avatar -->
            <!-- Details -->
            <div class="flex-1 space-y-4 py-1">
              <div class="h-4 bg-gray-400 rounded w-3/4"></div>
              <div class="space-y-2">
                <div class="h-4 bg-gray-400 rounded"></div>
                <div class="h-4 bg-gray-400 rounded w-5/6"></div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

<% elsif params[:view] == 'slides' %>
  <div class="container-fluid hidden md:block  p-6 rounded-lg border mb-2" style="background-color: #eff2f6;
    ">
    <style>
        .carousel-item {height:90vh !important;}
    </style>
    <%= turbo_frame_tag :slides, src: featured_event_slides_path, loading: :lazy do %>
      <div class="bg-gray-400 h-96 w-full "  >

      </div>
      <div class="bg-gray-400 h-44 w-full "  >

      </div>
    <% end %>
  </div>
<% elsif params[:view] == 'cards' %>
  <%= render(CardComponent.new(events: "e")) %>

<% else %>
  <section class="text-gray-600 body-font backgroundGradient">
    <div class="container-fluid px-5  mx-auto max-w-7x1" >
      <div class="row p-4 mb-4" >
        <div class="col-md-4 mb-6 lg:mb-0" >
          <%= image_tag('GHCC-Color-Logo_Events.svg', width: '100%', alt: 'Logo') %>
        </div>
      </div>
      <div class="row overflow">
        <div class="col-md-4 overflow">
          <%= turbo_frame_tag :list, src: list_events_path, loading: :lazy do %>
            <div class="flex flex-col space-y-6">
              <% 10.times do %>
                <div class=" p-6 rounded-lg border mb-2" style="background-color: #eff2f6" >
                <div class="animate-pulse flex space-x-4">
                  <!-- Avatar -->
                  <!-- Details -->
                  <div class="flex-1 space-y-4 py-1">
                    <div class="h-4 bg-gray-400 rounded w-3/4"></div>
                    <div class="space-y-2">
                      <div class="h-4 bg-gray-400 rounded"></div>
                      <div class="h-4 bg-gray-400 rounded w-5/6"></div>
                    </div>
                  </div>
                </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="col-md-8 " >
          <div class="container-fluid hidden md:block  p-6 rounded-lg border mb-2" style="background-color: #eff2f6;position: fixed;
            width: 63%;">
            <%= turbo_frame_tag :slides, src: featured_event_slides_path, loading: :lazy do %>
              <div class="bg-gray-400 w-full " style="height:76vh"  >
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>
<% end %>

app/views/events/list.html.erb
<%= turbo_frame_tag :list do %>
  <%= render(ListComponent.new(events: @events, month: @month)) %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%= turbo_frame_tag dom_id(@event) do %>
  <div class="xl:w-1/3 md:w-1/2 p-4 border mx-2">
    <div class="bg-white p-6 rounded-lg">
      <img class="lg:h-60 xl:h-56 md:h-64 sm:h-72 xs:h-72 h-72  rounded w-full object-cover object-center mb-6" src="<%= @event.event_details['image'] %>" alt="Image Size 720x400">
      <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font"><%= @event.event_details['recurrence_description'] %></h3>
      <h2 class="text-lg text-gray-900 font-medium title-font mb-4"><%= @event.event_details['name'] %></h2>
      <div class="h-1 -mt-2 w-20 bg-indigo-500 rounded"></div>
      <% if @event.event_details['description'].nil? %>
      <% else %>
        <p class="mt-4 leading-relaxed text-base"><%= @event.event_details['description'].html_safe %></p>
      <% end %>
      <% if @event.event_details['location'].nil? %>
      <% else %>
        <p class="mt-4 leading-relaxed text-sm">Location: <%= @event.event_details['location']['name'].present? ? @event.event_details['location']['name'] : '' %> - <%= @event.event_details['location']['street_address'].present? ? @event.event_details['location']['street_address'] : '' %><br>
          <%= @event.event_details['location']['city'].present? ? @event.event_details['location']['city'] : '' %>, <%= @event.event_details['location']['state'].present? ? @event.event_details['location']['state'] : '' %> <%= @event.event_details['location']['name'].present? ? @event.event_details['location']['zip'] : '' %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/events/slides.html.erb
<%= turbo_frame_tag :slides do %>
  <%= render(CarouselComponent.new(events: @events)) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>GHCC Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Golden Hills Community Church Upcoming Events">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
  <body>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

app/views/welcome/index.html.erb
<iframe src="https://ghcc-calendar.herokuapp.com" width="1920" height="1000" frameborder="0"></iframe>